//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 01:48:06 PM CET 
//


package xades4j.xml.bind.xades;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xades4j.xml.bind.xades package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnsignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedDataObjectProperties");
    private final static QName _IndividualDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "IndividualDataObjectsTimeStamp");
    private final static QName _SignatureTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureTimeStamp");
    private final static QName _AttrAuthoritiesCertValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttrAuthoritiesCertValues");
    private final static QName _SPUserNotice_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPUserNotice");
    private final static QName _RefsOnlyTimeStampV2_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "RefsOnlyTimeStampV2");
    private final static QName _UnsignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedProperties");
    private final static QName _CompleteRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteRevocationRefs");
    private final static QName _SignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedSignatureProperties");
    private final static QName _AttributeRevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationValues");
    private final static QName _ObjectIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ObjectIdentifier");
    private final static QName _OtherTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherTimeStamp");
    private final static QName _RefsOnlyTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RefsOnlyTimeStamp");
    private final static QName _SigningCertificateV2_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningCertificateV2");
    private final static QName _SPURI_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPURI");
    private final static QName _SignaturePolicyStore_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "SignaturePolicyStore");
    private final static QName _SignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedDataObjectProperties");
    private final static QName _CounterSignature_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CounterSignature");
    private final static QName _SignedAssertion_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedAssertion");
    private final static QName _QualifyingProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingProperties");
    private final static QName _SPDocSpecification_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "SPDocSpecification");
    private final static QName _RenewedDigests_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "RenewedDigests");
    private final static QName _SignatureProductionPlaceV2_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureProductionPlaceV2");
    private final static QName _SigningCertificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningCertificate");
    private final static QName _ArchiveTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "ArchiveTimeStamp");
    private final static QName _ReferenceInfo_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ReferenceInfo");
    private final static QName _CertifiedRolesV2_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertifiedRolesV2");
    private final static QName _X509AttributeCertificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "X509AttributeCertificate");
    private final static QName _SignatureProductionPlace_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureProductionPlace");
    private final static QName _XAdESTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "XAdESTimeStamp");
    private final static QName _EncapsulatedPKIData_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedPKIData");
    private final static QName _SigAndRefsTimeStampV2_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "SigAndRefsTimeStampV2");
    private final static QName _CommitmentTypeIndication_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CommitmentTypeIndication");
    private final static QName _UnsignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedSignatureProperties");
    private final static QName _AllDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AllDataObjectsTimeStamp");
    private final static QName _SignerRole_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignerRole");
    private final static QName _RevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RevocationValues");
    private final static QName _ClaimedRoles_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ClaimedRoles");
    private final static QName _SignerRoleV2_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignerRoleV2");
    private final static QName _QualifyingPropertiesReference_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingPropertiesReference");
    private final static QName _AttributeCertificateRefsV2_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "AttributeCertificateRefsV2");
    private final static QName _CertificateValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertificateValues");
    private final static QName _Any_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Any");
    private final static QName _SignaturePolicyIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignaturePolicyIdentifier");
    private final static QName _SigningTime_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningTime");
    private final static QName _OtherAttributeCertificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherAttributeCertificate");
    private final static QName _RecomputedDigestValue_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "RecomputedDigestValue");
    private final static QName _Include_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Include");
    private final static QName _SigAndRefsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigAndRefsTimeStamp");
    private final static QName _DataObjectFormat_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "DataObjectFormat");
    private final static QName _AttributeCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeCertificateRefs");
    private final static QName _TimeStampValidationData_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "TimeStampValidationData");
    private final static QName _SignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedProperties");
    private final static QName _CompleteCertificateRefsV2_QNAME = new QName("http://uri.etsi.org/01903/v1.4.1#", "CompleteCertificateRefsV2");
    private final static QName _CompleteCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteCertificateRefs");
    private final static QName _SignedAssertions_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedAssertions");
    private final static QName _AttributeRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationRefs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xades4j.xml.bind.xades
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlXAdESTimeStampType }
     * 
     */
    public XmlXAdESTimeStampType createXmlXAdESTimeStampType() {
        return new XmlXAdESTimeStampType();
    }

    /**
     * Create an instance of {@link XmlOCSPIdentifierType }
     * 
     */
    public XmlOCSPIdentifierType createXmlOCSPIdentifierType() {
        return new XmlOCSPIdentifierType();
    }

    /**
     * Create an instance of {@link XmlIdentifierType }
     * 
     */
    public XmlIdentifierType createXmlIdentifierType() {
        return new XmlIdentifierType();
    }

    /**
     * Create an instance of {@link XmlOCSPRefsType }
     * 
     */
    public XmlOCSPRefsType createXmlOCSPRefsType() {
        return new XmlOCSPRefsType();
    }

    /**
     * Create an instance of {@link XmlOCSPValuesType }
     * 
     */
    public XmlOCSPValuesType createXmlOCSPValuesType() {
        return new XmlOCSPValuesType();
    }

    /**
     * Create an instance of {@link XmlSignaturePolicyStoreType }
     * 
     */
    public XmlSignaturePolicyStoreType createXmlSignaturePolicyStoreType() {
        return new XmlSignaturePolicyStoreType();
    }

    /**
     * Create an instance of {@link XmlCompleteCertificateRefsType }
     * 
     */
    public XmlCompleteCertificateRefsType createXmlCompleteCertificateRefsType() {
        return new XmlCompleteCertificateRefsType();
    }

    /**
     * Create an instance of {@link XmlOtherTimeStampType }
     * 
     */
    public XmlOtherTimeStampType createXmlOtherTimeStampType() {
        return new XmlOtherTimeStampType();
    }

    /**
     * Create an instance of {@link XmlQualifyingPropertiesReferenceType }
     * 
     */
    public XmlQualifyingPropertiesReferenceType createXmlQualifyingPropertiesReferenceType() {
        return new XmlQualifyingPropertiesReferenceType();
    }

    /**
     * Create an instance of {@link XmlSigPolicyQualifiersListType }
     * 
     */
    public XmlSigPolicyQualifiersListType createXmlSigPolicyQualifiersListType() {
        return new XmlSigPolicyQualifiersListType();
    }

    /**
     * Create an instance of {@link XmlCertifiedRoleTypeV2 }
     * 
     */
    public XmlCertifiedRoleTypeV2 createXmlCertifiedRoleTypeV2() {
        return new XmlCertifiedRoleTypeV2();
    }

    /**
     * Create an instance of {@link XmlSignerRoleType }
     * 
     */
    public XmlSignerRoleType createXmlSignerRoleType() {
        return new XmlSignerRoleType();
    }

    /**
     * Create an instance of {@link XmlCertIDListType }
     * 
     */
    public XmlCertIDListType createXmlCertIDListType() {
        return new XmlCertIDListType();
    }

    /**
     * Create an instance of {@link XmlCounterSignatureType }
     * 
     */
    public XmlCounterSignatureType createXmlCounterSignatureType() {
        return new XmlCounterSignatureType();
    }

    /**
     * Create an instance of {@link XmlRenewedDigestsType }
     * 
     */
    public XmlRenewedDigestsType createXmlRenewedDigestsType() {
        return new XmlRenewedDigestsType();
    }

    /**
     * Create an instance of {@link XmlIntegerListType }
     * 
     */
    public XmlIntegerListType createXmlIntegerListType() {
        return new XmlIntegerListType();
    }

    /**
     * Create an instance of {@link XmlSignerRoleV2Type }
     * 
     */
    public XmlSignerRoleV2Type createXmlSignerRoleV2Type() {
        return new XmlSignerRoleV2Type();
    }

    /**
     * Create an instance of {@link XmlCRLValuesType }
     * 
     */
    public XmlCRLValuesType createXmlCRLValuesType() {
        return new XmlCRLValuesType();
    }

    /**
     * Create an instance of {@link XmlSignedPropertiesType }
     * 
     */
    public XmlSignedPropertiesType createXmlSignedPropertiesType() {
        return new XmlSignedPropertiesType();
    }

    /**
     * Create an instance of {@link XmlUnsignedPropertiesType }
     * 
     */
    public XmlUnsignedPropertiesType createXmlUnsignedPropertiesType() {
        return new XmlUnsignedPropertiesType();
    }

    /**
     * Create an instance of {@link XmlEncapsulatedPKIDataType }
     * 
     */
    public XmlEncapsulatedPKIDataType createXmlEncapsulatedPKIDataType() {
        return new XmlEncapsulatedPKIDataType();
    }

    /**
     * Create an instance of {@link XmlReferenceInfoType }
     * 
     */
    public XmlReferenceInfoType createXmlReferenceInfoType() {
        return new XmlReferenceInfoType();
    }

    /**
     * Create an instance of {@link XmlRecomputedDigestValueType }
     * 
     */
    public XmlRecomputedDigestValueType createXmlRecomputedDigestValueType() {
        return new XmlRecomputedDigestValueType();
    }

    /**
     * Create an instance of {@link XmlRevocationValuesType }
     * 
     */
    public XmlRevocationValuesType createXmlRevocationValuesType() {
        return new XmlRevocationValuesType();
    }

    /**
     * Create an instance of {@link XmlSignatureProductionPlaceType }
     * 
     */
    public XmlSignatureProductionPlaceType createXmlSignatureProductionPlaceType() {
        return new XmlSignatureProductionPlaceType();
    }

    /**
     * Create an instance of {@link XmlCertIDListV2Type }
     * 
     */
    public XmlCertIDListV2Type createXmlCertIDListV2Type() {
        return new XmlCertIDListV2Type();
    }

    /**
     * Create an instance of {@link XmlResponderIDType }
     * 
     */
    public XmlResponderIDType createXmlResponderIDType() {
        return new XmlResponderIDType();
    }

    /**
     * Create an instance of {@link XmlCompleteCertificateRefsTypeV2 }
     * 
     */
    public XmlCompleteCertificateRefsTypeV2 createXmlCompleteCertificateRefsTypeV2() {
        return new XmlCompleteCertificateRefsTypeV2();
    }

    /**
     * Create an instance of {@link XmlSignaturePolicyIdentifierType }
     * 
     */
    public XmlSignaturePolicyIdentifierType createXmlSignaturePolicyIdentifierType() {
        return new XmlSignaturePolicyIdentifierType();
    }

    /**
     * Create an instance of {@link XmlSPUserNoticeType }
     * 
     */
    public XmlSPUserNoticeType createXmlSPUserNoticeType() {
        return new XmlSPUserNoticeType();
    }

    /**
     * Create an instance of {@link XmlClaimedRolesListType }
     * 
     */
    public XmlClaimedRolesListType createXmlClaimedRolesListType() {
        return new XmlClaimedRolesListType();
    }

    /**
     * Create an instance of {@link XmlCompleteRevocationRefsType }
     * 
     */
    public XmlCompleteRevocationRefsType createXmlCompleteRevocationRefsType() {
        return new XmlCompleteRevocationRefsType();
    }

    /**
     * Create an instance of {@link XmlCertificateValuesType }
     * 
     */
    public XmlCertificateValuesType createXmlCertificateValuesType() {
        return new XmlCertificateValuesType();
    }

    /**
     * Create an instance of {@link XmlSignatureProductionPlaceV2Type }
     * 
     */
    public XmlSignatureProductionPlaceV2Type createXmlSignatureProductionPlaceV2Type() {
        return new XmlSignatureProductionPlaceV2Type();
    }

    /**
     * Create an instance of {@link XmlAnyType }
     * 
     */
    public XmlAnyType createXmlAnyType() {
        return new XmlAnyType();
    }

    /**
     * Create an instance of {@link XmlQualifyingPropertiesType }
     * 
     */
    public XmlQualifyingPropertiesType createXmlQualifyingPropertiesType() {
        return new XmlQualifyingPropertiesType();
    }

    /**
     * Create an instance of {@link XmlObjectIdentifierType }
     * 
     */
    public XmlObjectIdentifierType createXmlObjectIdentifierType() {
        return new XmlObjectIdentifierType();
    }

    /**
     * Create an instance of {@link XmlDocumentationReferencesType }
     * 
     */
    public XmlDocumentationReferencesType createXmlDocumentationReferencesType() {
        return new XmlDocumentationReferencesType();
    }

    /**
     * Create an instance of {@link XmlOCSPRefType }
     * 
     */
    public XmlOCSPRefType createXmlOCSPRefType() {
        return new XmlOCSPRefType();
    }

    /**
     * Create an instance of {@link XmlOtherCertStatusValuesType }
     * 
     */
    public XmlOtherCertStatusValuesType createXmlOtherCertStatusValuesType() {
        return new XmlOtherCertStatusValuesType();
    }

    /**
     * Create an instance of {@link XmlSignedSignaturePropertiesType }
     * 
     */
    public XmlSignedSignaturePropertiesType createXmlSignedSignaturePropertiesType() {
        return new XmlSignedSignaturePropertiesType();
    }

    /**
     * Create an instance of {@link XmlSignedDataObjectPropertiesType }
     * 
     */
    public XmlSignedDataObjectPropertiesType createXmlSignedDataObjectPropertiesType() {
        return new XmlSignedDataObjectPropertiesType();
    }

    /**
     * Create an instance of {@link XmlOtherCertStatusRefsType }
     * 
     */
    public XmlOtherCertStatusRefsType createXmlOtherCertStatusRefsType() {
        return new XmlOtherCertStatusRefsType();
    }

    /**
     * Create an instance of {@link XmlCertifiedRolesListType }
     * 
     */
    public XmlCertifiedRolesListType createXmlCertifiedRolesListType() {
        return new XmlCertifiedRolesListType();
    }

    /**
     * Create an instance of {@link XmlCertifiedRolesListTypeV2 }
     * 
     */
    public XmlCertifiedRolesListTypeV2 createXmlCertifiedRolesListTypeV2() {
        return new XmlCertifiedRolesListTypeV2();
    }

    /**
     * Create an instance of {@link XmlUnsignedSignaturePropertiesType }
     * 
     */
    public XmlUnsignedSignaturePropertiesType createXmlUnsignedSignaturePropertiesType() {
        return new XmlUnsignedSignaturePropertiesType();
    }

    /**
     * Create an instance of {@link XmlCertIDType }
     * 
     */
    public XmlCertIDType createXmlCertIDType() {
        return new XmlCertIDType();
    }

    /**
     * Create an instance of {@link XmlDataObjectFormatType }
     * 
     */
    public XmlDataObjectFormatType createXmlDataObjectFormatType() {
        return new XmlDataObjectFormatType();
    }

    /**
     * Create an instance of {@link XmlUnsignedDataObjectPropertiesType }
     * 
     */
    public XmlUnsignedDataObjectPropertiesType createXmlUnsignedDataObjectPropertiesType() {
        return new XmlUnsignedDataObjectPropertiesType();
    }

    /**
     * Create an instance of {@link XmlCommitmentTypeIndicationType }
     * 
     */
    public XmlCommitmentTypeIndicationType createXmlCommitmentTypeIndicationType() {
        return new XmlCommitmentTypeIndicationType();
    }

    /**
     * Create an instance of {@link XmlIncludeType }
     * 
     */
    public XmlIncludeType createXmlIncludeType() {
        return new XmlIncludeType();
    }

    /**
     * Create an instance of {@link XmlNoticeReferenceType }
     * 
     */
    public XmlNoticeReferenceType createXmlNoticeReferenceType() {
        return new XmlNoticeReferenceType();
    }

    /**
     * Create an instance of {@link XmlCRLIdentifierType }
     * 
     */
    public XmlCRLIdentifierType createXmlCRLIdentifierType() {
        return new XmlCRLIdentifierType();
    }

    /**
     * Create an instance of {@link XmlDigestAlgAndValueType }
     * 
     */
    public XmlDigestAlgAndValueType createXmlDigestAlgAndValueType() {
        return new XmlDigestAlgAndValueType();
    }

    /**
     * Create an instance of {@link XmlCRLRefType }
     * 
     */
    public XmlCRLRefType createXmlCRLRefType() {
        return new XmlCRLRefType();
    }

    /**
     * Create an instance of {@link XmlCommitmentTypeQualifiersListType }
     * 
     */
    public XmlCommitmentTypeQualifiersListType createXmlCommitmentTypeQualifiersListType() {
        return new XmlCommitmentTypeQualifiersListType();
    }

    /**
     * Create an instance of {@link XmlCRLRefsType }
     * 
     */
    public XmlCRLRefsType createXmlCRLRefsType() {
        return new XmlCRLRefsType();
    }

    /**
     * Create an instance of {@link XmlCertIDTypeV2 }
     * 
     */
    public XmlCertIDTypeV2 createXmlCertIDTypeV2() {
        return new XmlCertIDTypeV2();
    }

    /**
     * Create an instance of {@link XmlSignaturePolicyIdType }
     * 
     */
    public XmlSignaturePolicyIdType createXmlSignaturePolicyIdType() {
        return new XmlSignaturePolicyIdType();
    }

    /**
     * Create an instance of {@link XmlValidationDataType }
     * 
     */
    public XmlValidationDataType createXmlValidationDataType() {
        return new XmlValidationDataType();
    }

    /**
     * Create an instance of {@link XmlSignedAssertionsListType }
     * 
     */
    public XmlSignedAssertionsListType createXmlSignedAssertionsListType() {
        return new XmlSignedAssertionsListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlUnsignedDataObjectPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedDataObjectProperties")
    public JAXBElement<XmlUnsignedDataObjectPropertiesType> createUnsignedDataObjectProperties(XmlUnsignedDataObjectPropertiesType value) {
        return new JAXBElement<XmlUnsignedDataObjectPropertiesType>(_UnsignedDataObjectProperties_QNAME, XmlUnsignedDataObjectPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "IndividualDataObjectsTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createIndividualDataObjectsTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_IndividualDataObjectsTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createSignatureTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_SignatureTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertificateValuesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttrAuthoritiesCertValues")
    public JAXBElement<XmlCertificateValuesType> createAttrAuthoritiesCertValues(XmlCertificateValuesType value) {
        return new JAXBElement<XmlCertificateValuesType>(_AttrAuthoritiesCertValues_QNAME, XmlCertificateValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSPUserNoticeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SPUserNotice")
    public JAXBElement<XmlSPUserNoticeType> createSPUserNotice(XmlSPUserNoticeType value) {
        return new JAXBElement<XmlSPUserNoticeType>(_SPUserNotice_QNAME, XmlSPUserNoticeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "RefsOnlyTimeStampV2")
    public JAXBElement<XmlXAdESTimeStampType> createRefsOnlyTimeStampV2(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_RefsOnlyTimeStampV2_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlUnsignedPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedProperties")
    public JAXBElement<XmlUnsignedPropertiesType> createUnsignedProperties(XmlUnsignedPropertiesType value) {
        return new JAXBElement<XmlUnsignedPropertiesType>(_UnsignedProperties_QNAME, XmlUnsignedPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteRevocationRefsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteRevocationRefs")
    public JAXBElement<XmlCompleteRevocationRefsType> createCompleteRevocationRefs(XmlCompleteRevocationRefsType value) {
        return new JAXBElement<XmlCompleteRevocationRefsType>(_CompleteRevocationRefs_QNAME, XmlCompleteRevocationRefsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignedSignaturePropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedSignatureProperties")
    public JAXBElement<XmlSignedSignaturePropertiesType> createSignedSignatureProperties(XmlSignedSignaturePropertiesType value) {
        return new JAXBElement<XmlSignedSignaturePropertiesType>(_SignedSignatureProperties_QNAME, XmlSignedSignaturePropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRevocationValuesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationValues")
    public JAXBElement<XmlRevocationValuesType> createAttributeRevocationValues(XmlRevocationValuesType value) {
        return new JAXBElement<XmlRevocationValuesType>(_AttributeRevocationValues_QNAME, XmlRevocationValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlObjectIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ObjectIdentifier")
    public JAXBElement<XmlObjectIdentifierType> createObjectIdentifier(XmlObjectIdentifierType value) {
        return new JAXBElement<XmlObjectIdentifierType>(_ObjectIdentifier_QNAME, XmlObjectIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlOtherTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherTimeStamp")
    public JAXBElement<XmlOtherTimeStampType> createOtherTimeStamp(XmlOtherTimeStampType value) {
        return new JAXBElement<XmlOtherTimeStampType>(_OtherTimeStamp_QNAME, XmlOtherTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RefsOnlyTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createRefsOnlyTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_RefsOnlyTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertIDListV2Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigningCertificateV2")
    public JAXBElement<XmlCertIDListV2Type> createSigningCertificateV2(XmlCertIDListV2Type value) {
        return new JAXBElement<XmlCertIDListV2Type>(_SigningCertificateV2_QNAME, XmlCertIDListV2Type.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SPURI")
    public JAXBElement<String> createSPURI(String value) {
        return new JAXBElement<String>(_SPURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignaturePolicyStoreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "SignaturePolicyStore")
    public JAXBElement<XmlSignaturePolicyStoreType> createSignaturePolicyStore(XmlSignaturePolicyStoreType value) {
        return new JAXBElement<XmlSignaturePolicyStoreType>(_SignaturePolicyStore_QNAME, XmlSignaturePolicyStoreType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignedDataObjectPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedDataObjectProperties")
    public JAXBElement<XmlSignedDataObjectPropertiesType> createSignedDataObjectProperties(XmlSignedDataObjectPropertiesType value) {
        return new JAXBElement<XmlSignedDataObjectPropertiesType>(_SignedDataObjectProperties_QNAME, XmlSignedDataObjectPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCounterSignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CounterSignature")
    public JAXBElement<XmlCounterSignatureType> createCounterSignature(XmlCounterSignatureType value) {
        return new JAXBElement<XmlCounterSignatureType>(_CounterSignature_QNAME, XmlCounterSignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedAssertion")
    public JAXBElement<XmlAnyType> createSignedAssertion(XmlAnyType value) {
        return new JAXBElement<XmlAnyType>(_SignedAssertion_QNAME, XmlAnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlQualifyingPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "QualifyingProperties")
    public JAXBElement<XmlQualifyingPropertiesType> createQualifyingProperties(XmlQualifyingPropertiesType value) {
        return new JAXBElement<XmlQualifyingPropertiesType>(_QualifyingProperties_QNAME, XmlQualifyingPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlObjectIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "SPDocSpecification")
    public JAXBElement<XmlObjectIdentifierType> createSPDocSpecification(XmlObjectIdentifierType value) {
        return new JAXBElement<XmlObjectIdentifierType>(_SPDocSpecification_QNAME, XmlObjectIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRenewedDigestsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "RenewedDigests")
    public JAXBElement<XmlRenewedDigestsType> createRenewedDigests(XmlRenewedDigestsType value) {
        return new JAXBElement<XmlRenewedDigestsType>(_RenewedDigests_QNAME, XmlRenewedDigestsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignatureProductionPlaceV2Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureProductionPlaceV2")
    public JAXBElement<XmlSignatureProductionPlaceV2Type> createSignatureProductionPlaceV2(XmlSignatureProductionPlaceV2Type value) {
        return new JAXBElement<XmlSignatureProductionPlaceV2Type>(_SignatureProductionPlaceV2_QNAME, XmlSignatureProductionPlaceV2Type.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertIDListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigningCertificate")
    public JAXBElement<XmlCertIDListType> createSigningCertificate(XmlCertIDListType value) {
        return new JAXBElement<XmlCertIDListType>(_SigningCertificate_QNAME, XmlCertIDListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "ArchiveTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createArchiveTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_ArchiveTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlReferenceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ReferenceInfo")
    public JAXBElement<XmlReferenceInfoType> createReferenceInfo(XmlReferenceInfoType value) {
        return new JAXBElement<XmlReferenceInfoType>(_ReferenceInfo_QNAME, XmlReferenceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertifiedRolesListTypeV2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertifiedRolesV2")
    public JAXBElement<XmlCertifiedRolesListTypeV2> createCertifiedRolesV2(XmlCertifiedRolesListTypeV2 value) {
        return new JAXBElement<XmlCertifiedRolesListTypeV2>(_CertifiedRolesV2_QNAME, XmlCertifiedRolesListTypeV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlEncapsulatedPKIDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "X509AttributeCertificate")
    public JAXBElement<XmlEncapsulatedPKIDataType> createX509AttributeCertificate(XmlEncapsulatedPKIDataType value) {
        return new JAXBElement<XmlEncapsulatedPKIDataType>(_X509AttributeCertificate_QNAME, XmlEncapsulatedPKIDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignatureProductionPlaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureProductionPlace")
    public JAXBElement<XmlSignatureProductionPlaceType> createSignatureProductionPlace(XmlSignatureProductionPlaceType value) {
        return new JAXBElement<XmlSignatureProductionPlaceType>(_SignatureProductionPlace_QNAME, XmlSignatureProductionPlaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "XAdESTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createXAdESTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_XAdESTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlEncapsulatedPKIDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "EncapsulatedPKIData")
    public JAXBElement<XmlEncapsulatedPKIDataType> createEncapsulatedPKIData(XmlEncapsulatedPKIDataType value) {
        return new JAXBElement<XmlEncapsulatedPKIDataType>(_EncapsulatedPKIData_QNAME, XmlEncapsulatedPKIDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "SigAndRefsTimeStampV2")
    public JAXBElement<XmlXAdESTimeStampType> createSigAndRefsTimeStampV2(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_SigAndRefsTimeStampV2_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCommitmentTypeIndicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CommitmentTypeIndication")
    public JAXBElement<XmlCommitmentTypeIndicationType> createCommitmentTypeIndication(XmlCommitmentTypeIndicationType value) {
        return new JAXBElement<XmlCommitmentTypeIndicationType>(_CommitmentTypeIndication_QNAME, XmlCommitmentTypeIndicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlUnsignedSignaturePropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedSignatureProperties")
    public JAXBElement<XmlUnsignedSignaturePropertiesType> createUnsignedSignatureProperties(XmlUnsignedSignaturePropertiesType value) {
        return new JAXBElement<XmlUnsignedSignaturePropertiesType>(_UnsignedSignatureProperties_QNAME, XmlUnsignedSignaturePropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AllDataObjectsTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createAllDataObjectsTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_AllDataObjectsTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignerRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignerRole")
    public JAXBElement<XmlSignerRoleType> createSignerRole(XmlSignerRoleType value) {
        return new JAXBElement<XmlSignerRoleType>(_SignerRole_QNAME, XmlSignerRoleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRevocationValuesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RevocationValues")
    public JAXBElement<XmlRevocationValuesType> createRevocationValues(XmlRevocationValuesType value) {
        return new JAXBElement<XmlRevocationValuesType>(_RevocationValues_QNAME, XmlRevocationValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlClaimedRolesListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ClaimedRoles")
    public JAXBElement<XmlClaimedRolesListType> createClaimedRoles(XmlClaimedRolesListType value) {
        return new JAXBElement<XmlClaimedRolesListType>(_ClaimedRoles_QNAME, XmlClaimedRolesListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignerRoleV2Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignerRoleV2")
    public JAXBElement<XmlSignerRoleV2Type> createSignerRoleV2(XmlSignerRoleV2Type value) {
        return new JAXBElement<XmlSignerRoleV2Type>(_SignerRoleV2_QNAME, XmlSignerRoleV2Type.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlQualifyingPropertiesReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "QualifyingPropertiesReference")
    public JAXBElement<XmlQualifyingPropertiesReferenceType> createQualifyingPropertiesReference(XmlQualifyingPropertiesReferenceType value) {
        return new JAXBElement<XmlQualifyingPropertiesReferenceType>(_QualifyingPropertiesReference_QNAME, XmlQualifyingPropertiesReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsTypeV2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "AttributeCertificateRefsV2")
    public JAXBElement<XmlCompleteCertificateRefsTypeV2> createAttributeCertificateRefsV2(XmlCompleteCertificateRefsTypeV2 value) {
        return new JAXBElement<XmlCompleteCertificateRefsTypeV2>(_AttributeCertificateRefsV2_QNAME, XmlCompleteCertificateRefsTypeV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCertificateValuesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertificateValues")
    public JAXBElement<XmlCertificateValuesType> createCertificateValues(XmlCertificateValuesType value) {
        return new JAXBElement<XmlCertificateValuesType>(_CertificateValues_QNAME, XmlCertificateValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Any")
    public JAXBElement<XmlAnyType> createAny(XmlAnyType value) {
        return new JAXBElement<XmlAnyType>(_Any_QNAME, XmlAnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignaturePolicyIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignaturePolicyIdentifier")
    public JAXBElement<XmlSignaturePolicyIdentifierType> createSignaturePolicyIdentifier(XmlSignaturePolicyIdentifierType value) {
        return new JAXBElement<XmlSignaturePolicyIdentifierType>(_SignaturePolicyIdentifier_QNAME, XmlSignaturePolicyIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigningTime")
    public JAXBElement<XMLGregorianCalendar> createSigningTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SigningTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherAttributeCertificate")
    public JAXBElement<XmlAnyType> createOtherAttributeCertificate(XmlAnyType value) {
        return new JAXBElement<XmlAnyType>(_OtherAttributeCertificate_QNAME, XmlAnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlRecomputedDigestValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "RecomputedDigestValue")
    public JAXBElement<XmlRecomputedDigestValueType> createRecomputedDigestValue(XmlRecomputedDigestValueType value) {
        return new JAXBElement<XmlRecomputedDigestValueType>(_RecomputedDigestValue_QNAME, XmlRecomputedDigestValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlIncludeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Include")
    public JAXBElement<XmlIncludeType> createInclude(XmlIncludeType value) {
        return new JAXBElement<XmlIncludeType>(_Include_QNAME, XmlIncludeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlXAdESTimeStampType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigAndRefsTimeStamp")
    public JAXBElement<XmlXAdESTimeStampType> createSigAndRefsTimeStamp(XmlXAdESTimeStampType value) {
        return new JAXBElement<XmlXAdESTimeStampType>(_SigAndRefsTimeStamp_QNAME, XmlXAdESTimeStampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlDataObjectFormatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "DataObjectFormat")
    public JAXBElement<XmlDataObjectFormatType> createDataObjectFormat(XmlDataObjectFormatType value) {
        return new JAXBElement<XmlDataObjectFormatType>(_DataObjectFormat_QNAME, XmlDataObjectFormatType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeCertificateRefs")
    public JAXBElement<XmlCompleteCertificateRefsType> createAttributeCertificateRefs(XmlCompleteCertificateRefsType value) {
        return new JAXBElement<XmlCompleteCertificateRefsType>(_AttributeCertificateRefs_QNAME, XmlCompleteCertificateRefsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlValidationDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "TimeStampValidationData")
    public JAXBElement<XmlValidationDataType> createTimeStampValidationData(XmlValidationDataType value) {
        return new JAXBElement<XmlValidationDataType>(_TimeStampValidationData_QNAME, XmlValidationDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignedPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedProperties")
    public JAXBElement<XmlSignedPropertiesType> createSignedProperties(XmlSignedPropertiesType value) {
        return new JAXBElement<XmlSignedPropertiesType>(_SignedProperties_QNAME, XmlSignedPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsTypeV2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.4.1#", name = "CompleteCertificateRefsV2")
    public JAXBElement<XmlCompleteCertificateRefsTypeV2> createCompleteCertificateRefsV2(XmlCompleteCertificateRefsTypeV2 value) {
        return new JAXBElement<XmlCompleteCertificateRefsTypeV2>(_CompleteCertificateRefsV2_QNAME, XmlCompleteCertificateRefsTypeV2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteCertificateRefsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteCertificateRefs")
    public JAXBElement<XmlCompleteCertificateRefsType> createCompleteCertificateRefs(XmlCompleteCertificateRefsType value) {
        return new JAXBElement<XmlCompleteCertificateRefsType>(_CompleteCertificateRefs_QNAME, XmlCompleteCertificateRefsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSignedAssertionsListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedAssertions")
    public JAXBElement<XmlSignedAssertionsListType> createSignedAssertions(XmlSignedAssertionsListType value) {
        return new JAXBElement<XmlSignedAssertionsListType>(_SignedAssertions_QNAME, XmlSignedAssertionsListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompleteRevocationRefsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationRefs")
    public JAXBElement<XmlCompleteRevocationRefsType> createAttributeRevocationRefs(XmlCompleteRevocationRefsType value) {
        return new JAXBElement<XmlCompleteRevocationRefsType>(_AttributeRevocationRefs_QNAME, XmlCompleteRevocationRefsType.class, null, value);
    }

}
