//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 01:48:06 PM CET 
//


package xades4j.xml.bind.xades;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertifiedRoleTypeV2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertifiedRoleTypeV2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}X509AttributeCertificate"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}OtherAttributeCertificate"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertifiedRoleTypeV2", propOrder = {
    "x509AttributeCertificate",
    "otherAttributeCertificate"
})
public class XmlCertifiedRoleTypeV2 {

    @XmlElement(name = "X509AttributeCertificate")
    protected XmlEncapsulatedPKIDataType x509AttributeCertificate;
    @XmlElement(name = "OtherAttributeCertificate")
    protected XmlAnyType otherAttributeCertificate;

    /**
     * Gets the value of the x509AttributeCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link XmlEncapsulatedPKIDataType }
     *     
     */
    public XmlEncapsulatedPKIDataType getX509AttributeCertificate() {
        return x509AttributeCertificate;
    }

    /**
     * Sets the value of the x509AttributeCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlEncapsulatedPKIDataType }
     *     
     */
    public void setX509AttributeCertificate(XmlEncapsulatedPKIDataType value) {
        this.x509AttributeCertificate = value;
    }

    /**
     * Gets the value of the otherAttributeCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link XmlAnyType }
     *     
     */
    public XmlAnyType getOtherAttributeCertificate() {
        return otherAttributeCertificate;
    }

    /**
     * Sets the value of the otherAttributeCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlAnyType }
     *     
     */
    public void setOtherAttributeCertificate(XmlAnyType value) {
        this.otherAttributeCertificate = value;
    }

}
