//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 01:48:06 PM CET 
//


package xades4j.xml.bind.xades;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import xades4j.xml.bind.Base64XmlAdapter;


/**
 * <p>Java class for SignaturePolicyStoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignaturePolicyStoreType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.4.1#}SPDocSpecification"/>
 *         &lt;choice>
 *           &lt;element name="SignaturePolicyDocument" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *           &lt;element name="SigPolDocLocalURI" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignaturePolicyStoreType", namespace = "http://uri.etsi.org/01903/v1.4.1#", propOrder = {
    "spDocSpecification",
    "signaturePolicyDocument",
    "sigPolDocLocalURI"
})
public class XmlSignaturePolicyStoreType {

    @XmlElement(name = "SPDocSpecification", required = true)
    protected XmlObjectIdentifierType spDocSpecification;
    @XmlElement(name = "SignaturePolicyDocument", type = String.class)
    @XmlJavaTypeAdapter(Base64XmlAdapter .class)
    @XmlSchemaType(name = "base64Binary")
    protected byte[] signaturePolicyDocument;
    @XmlElement(name = "SigPolDocLocalURI")
    @XmlSchemaType(name = "anyURI")
    protected String sigPolDocLocalURI;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the spDocSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link XmlObjectIdentifierType }
     *     
     */
    public XmlObjectIdentifierType getSPDocSpecification() {
        return spDocSpecification;
    }

    /**
     * Sets the value of the spDocSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlObjectIdentifierType }
     *     
     */
    public void setSPDocSpecification(XmlObjectIdentifierType value) {
        this.spDocSpecification = value;
    }

    /**
     * Gets the value of the signaturePolicyDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSignaturePolicyDocument() {
        return signaturePolicyDocument;
    }

    /**
     * Sets the value of the signaturePolicyDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignaturePolicyDocument(byte[] value) {
        this.signaturePolicyDocument = value;
    }

    /**
     * Gets the value of the sigPolDocLocalURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigPolDocLocalURI() {
        return sigPolDocLocalURI;
    }

    /**
     * Sets the value of the sigPolDocLocalURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigPolDocLocalURI(String value) {
        this.sigPolDocLocalURI = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
