//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 01:48:06 PM CET 
//


package xades4j.xml.bind.xades;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import xades4j.xml.bind.DateTimeXmlAdapter;


/**
 * <p>Java class for SignedSignaturePropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignedSignaturePropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SigningTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SigningCertificate" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SigningCertificateV2" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SignaturePolicyIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SignatureProductionPlace" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SignatureProductionPlaceV2" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SignerRole" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SignerRoleV2" minOccurs="0"/>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignedSignaturePropertiesType", propOrder = {
    "signingTime",
    "signingCertificate",
    "signingCertificateV2",
    "signaturePolicyIdentifier",
    "signatureProductionPlace",
    "signatureProductionPlaceV2",
    "signerRole",
    "signerRoleV2",
    "any"
})
public class XmlSignedSignaturePropertiesType {

    @XmlElement(name = "SigningTime", type = String.class)
    @XmlJavaTypeAdapter(DateTimeXmlAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar signingTime;
    @XmlElement(name = "SigningCertificate")
    protected XmlCertIDListType signingCertificate;
    @XmlElement(name = "SigningCertificateV2")
    protected XmlCertIDListV2Type signingCertificateV2;
    @XmlElement(name = "SignaturePolicyIdentifier")
    protected XmlSignaturePolicyIdentifierType signaturePolicyIdentifier;
    @XmlElement(name = "SignatureProductionPlace")
    protected XmlSignatureProductionPlaceType signatureProductionPlace;
    @XmlElement(name = "SignatureProductionPlaceV2")
    protected XmlSignatureProductionPlaceV2Type signatureProductionPlaceV2;
    @XmlElement(name = "SignerRole")
    protected XmlSignerRoleType signerRole;
    @XmlElement(name = "SignerRoleV2")
    protected XmlSignerRoleV2Type signerRoleV2;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the signingTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Calendar getSigningTime() {
        return signingTime;
    }

    /**
     * Sets the value of the signingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSigningTime(Calendar value) {
        this.signingTime = value;
    }

    /**
     * Gets the value of the signingCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCertIDListType }
     *     
     */
    public XmlCertIDListType getSigningCertificate() {
        return signingCertificate;
    }

    /**
     * Sets the value of the signingCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCertIDListType }
     *     
     */
    public void setSigningCertificate(XmlCertIDListType value) {
        this.signingCertificate = value;
    }

    /**
     * Gets the value of the signingCertificateV2 property.
     * 
     * @return
     *     possible object is
     *     {@link XmlCertIDListV2Type }
     *     
     */
    public XmlCertIDListV2Type getSigningCertificateV2() {
        return signingCertificateV2;
    }

    /**
     * Sets the value of the signingCertificateV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlCertIDListV2Type }
     *     
     */
    public void setSigningCertificateV2(XmlCertIDListV2Type value) {
        this.signingCertificateV2 = value;
    }

    /**
     * Gets the value of the signaturePolicyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link XmlSignaturePolicyIdentifierType }
     *     
     */
    public XmlSignaturePolicyIdentifierType getSignaturePolicyIdentifier() {
        return signaturePolicyIdentifier;
    }

    /**
     * Sets the value of the signaturePolicyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlSignaturePolicyIdentifierType }
     *     
     */
    public void setSignaturePolicyIdentifier(XmlSignaturePolicyIdentifierType value) {
        this.signaturePolicyIdentifier = value;
    }

    /**
     * Gets the value of the signatureProductionPlace property.
     * 
     * @return
     *     possible object is
     *     {@link XmlSignatureProductionPlaceType }
     *     
     */
    public XmlSignatureProductionPlaceType getSignatureProductionPlace() {
        return signatureProductionPlace;
    }

    /**
     * Sets the value of the signatureProductionPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlSignatureProductionPlaceType }
     *     
     */
    public void setSignatureProductionPlace(XmlSignatureProductionPlaceType value) {
        this.signatureProductionPlace = value;
    }

    /**
     * Gets the value of the signatureProductionPlaceV2 property.
     * 
     * @return
     *     possible object is
     *     {@link XmlSignatureProductionPlaceV2Type }
     *     
     */
    public XmlSignatureProductionPlaceV2Type getSignatureProductionPlaceV2() {
        return signatureProductionPlaceV2;
    }

    /**
     * Sets the value of the signatureProductionPlaceV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlSignatureProductionPlaceV2Type }
     *     
     */
    public void setSignatureProductionPlaceV2(XmlSignatureProductionPlaceV2Type value) {
        this.signatureProductionPlaceV2 = value;
    }

    /**
     * Gets the value of the signerRole property.
     * 
     * @return
     *     possible object is
     *     {@link XmlSignerRoleType }
     *     
     */
    public XmlSignerRoleType getSignerRole() {
        return signerRole;
    }

    /**
     * Sets the value of the signerRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlSignerRoleType }
     *     
     */
    public void setSignerRole(XmlSignerRoleType value) {
        this.signerRole = value;
    }

    /**
     * Gets the value of the signerRoleV2 property.
     * 
     * @return
     *     possible object is
     *     {@link XmlSignerRoleV2Type }
     *     
     */
    public XmlSignerRoleV2Type getSignerRoleV2() {
        return signerRoleV2;
    }

    /**
     * Sets the value of the signerRoleV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlSignerRoleV2Type }
     *     
     */
    public void setSignerRoleV2(XmlSignerRoleV2Type value) {
        this.signerRoleV2 = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
